export const API_ENDPOINTS = {
  ITEMS: '/items',
  HEALTH: '/health'
};

export const UI_CONSTANTS = {
  DEBOUNCE_DELAY: 300,
  TOAST_DURATION: 3000,
  MODAL_ANIMATION_DURATION: 200
};

export const VALIDATION_RULES = {
  ITEM_NAME_MAX_LENGTH: 100,
  ITEM_DESCRIPTION_MAX_LENGTH: 500,
  ITEM_PRICE_MAX: 999999.99
};
