name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'  # Remove 'frontend/'
        
    - name: Install dependencies
      run: npm ci  # Remove 'cd frontend'
        
    - name: Run dummy CI checks
      run: |
        echo "Running frontend CI checks..."
        npm run build
        echo "✅ Build successful"
        echo "✅ All frontend CI checks completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        npx vercel --token $VERCEL_TOKEN --prod